--- name:default
# Joint Names used for this task
joint_names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
              "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
              "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
              "J_Pan", "J_Tilt"]

# Proportional controller parameters. Size has to be same as joint names
kp:
  data: [2.0, 2.0, 2.0, 2.0,
         2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 
         2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
         2.0, 2.0]

# Proportional controller parameters. Size has to be same as joint names.
kd:
  data: [0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
         0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
         0.0, 0.0]

# Max controller output. Size has to be either the same as joint_names or left 
#               empty, in which case infinite ctrl output will be allowed
max_ctrl_out:
  data: [0.2, 0.1, 0.1, 0.2,
         0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
         0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
         0.5, 0.5]
