--- name:default
# This is the 'end effector' frame of the controlled motion
controlled_frame_frame: 'Hand_r'

# This is the base frame of the controller motion, e.g. the robot base frame
controlled_in_frame: 'Chest'

# Max. cartesian velocities and accelerations can be defined here. If left empty, infinite ctrl output will be allowed.
max_ctrl_out:
  velocity:
    data:
    - .nan
    - .nan
    - .nan
  angular_velocity:
    data:
    - .nan
    - .nan
    - .nan
  acceleration:
    data:
    - .nan
    - .nan
    - .nan
  angular_acceleration:
    data:
    - .nan
    - .nan
    - .nan

# PID Controller parameters. Size has to be 6!
#             I-Value will be ignored. 
pid: 
   - kp: 0.01
     kd: 0.0
   - kp: 0.01
     kd: 0.0
   - kp: 0.01
     kd: 0.0
   - kp: 0.01
     kd: 0.0
   - kp: 0.01
     kd: 0.0
   - kp: 0.01
     kd: 0.0

# This is the setpoint frame of the controller motion, e.g. the control target
setpoint_frame: 'setpoint'

# list of static transformations
static_transformations: []

# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.1

# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0

