--- name:default
# Maximum influence distance per joint. Has to have same size as joint_names.
d_zero:
  data: [0.2, 0.05, 0.05, 0.2,
         0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,    
         0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
         0.05, 0.05]

# Note: Avoidance will be only done for the joints defined in the joint_names property.
joint_limits:
  names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
          "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
          "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
          "J_Pan", "J_Tilt"]
  elements: [{max: {position: 1.919862175, speed: 0.5, effort: 2.0}, min: {position: -1.919862175}}, # J_Foot
             {max: {position: 2.705260337, speed: 0.5, effort: 2.0}, min: {position: 2.1816615625}}, # J_Knees
             {max: {position: 2.705260337, speed: 0.5, effort: 2.0}, min: {position: 1.919862175 }}, # J_Hip
             {max: {position: 1.04719755,  speed: 0.5, effort: 2.0}, min: {position: -1.04719755 }}, # J_Waist
             {max: {position: 0.872664625, speed: 1.5, effort: 4.0}, min: {position: -1.74532925 }}, # J_Shoulder1_r
             {max: {position: 1.483529862, speed: 1.5, effort: 4.0}, min: {position: -0.087266462}}, # J_Shoulder2_r
             {max: {position: 1.919862175, speed: 1.5, effort: 4.0}, min: {position: -1.919862175}}, # J_UpperArm_r
             {max: {position: 1.832595712, speed: 1.5, effort: 4.0}, min: {position: -0.087266462}}, # J_Elbow_r
             {max: {position: 1.570796325, speed: 1.5, effort: 4.0}, min: {position: -1.919862175}}, # J_Forearm_r
             {max: {position: 0.0,         speed: 1.5, effort: 4.0}, min: {position: -1.570796325}}, # J_Wrist1_r
             {max: {position: 0.610865237, speed: 1.5, effort: 4.0}, min: {position: -0.261799387}}, # J_Wrist2_r
             {max: {position: 1.74532925,  speed: 1.5, effort: 4.0}, min: {position: -0.872664625}}, # J_Shoulder1_l
             {max: {position: 0.087266462, speed: 1.5, effort: 4.0}, min: {position: -1.483529862}}, # J_Shoulder2_l
             {max: {position: 1.919862175, speed: 1.5, effort: 4.0}, min: {position: -1.919862175}}, # J_UpperArm_l
             {max: {position: 0.087266462, speed: 1.5, effort: 4.0}, min: {position: -1.832595712}}, # J_Elbow_l
             {max: {position: 1.570796325, speed: 1.5, effort: 4.0}, min: {position: -1.919862175}}, # J_Forearm_l
             {max: {position: 0.0,         speed: 1.5, effort: 4.0}, min: {position: -1.570796325}}, # J_Wrist1_l
             {max: {position: 0.261799387, speed: 1.5, effort: 4.0}, min: {position: -0.610865237}}, # J_Wrist2_l
             {max: {position: 0.785398162, speed: 1.0, effort: 4.0}, min: {position: -0.6981317  }}, # J_Pan
             {max: {position: 0.523598775, speed: 1.0, effort: 4.0}, min: {position: -1.04719755 }}] # J_Tilt

# Proportional gain. Has to have same size as joint_names.
kp:
  data: [0.1,0.1,0.1,0.1,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         0.1,0.1]

max_ctrl_out:
  data: [0.05, 0.05, 0.05, 0.05, 
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
         0.1, 0.1]

# Transition range in percentage of the maximum influence distance. Has to be within 0..1.
#              Activation function is a piecewise linear function, that increases from 0 to 1.
#              The higher this value, the smaller the incline of the activation function.
#              For transition_range = 0, the activation will be a step function.
transition_range: 1
