
--- name:cart_pos_ctrl_right_arm
# This is the base frame of the controller motion, e.g. the robot base frame
controlled_in_frame: 'base_link'

# This is the 'end effector' frame of the controlled motion
controlled_frame_frame: 'Hand_r'

# This is the setpoint frame of the controller motion, e.g. the control target
setpoint_frame: 'setpoint_hand_r'

# Proportional controller parameters.
kp:
  data: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

# Proportional controller parameters.
kd:
  data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# Maximum controller output.
max_ctrl_out:
  data: [0.2, 0.2, 0.2, 0.4, 0.4, 0.4]
  
# Dead zone for each dof. If ctrl error is below that value, no control action takes place for that dof.
dead_zone:
   data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
