--- name:default
# Want a specific order of joints used in the Jacobians? If not, leave empty!
joint_names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
              "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
              "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
              "J_Pan", "J_Tilt"]

# Optionally define sub chains if not the complete KDL tree shall be used.
reduced_tree: 
    - root: Rover_base
      tip: Hand_r
    - root: Chest
      tip: Hand_l
    - root: Chest
      tip: LeftCamera
    - root: Forearm_r
      tip: Force_Sensor_r
    - root: Forearm_l
      tip: Force_Sensor_l

# URDF model file.
urdf: <%= "#{Bundles.find_file('data/aila.urdf')}" %>

# List of Task Frames. All ids given here must be valid links of the KDL Tree
task_frame_ids: ["Hand_r", "Rover_base"]
