--- name:default

# Define order of Joints that is used internally (for easier debugging)
joint_names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
              "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
              "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l"]

# Configuration of subtasks
wbc_config: 
   - name: force_ctrl_right_arm
     type: cart
     root: "Rover_base"
     tip: "Force_Sensor_r"
     ref_frame: constraint_ref_frame_tip
     priority: 0
   - name: force_ctrl_left_arm
     type: cart
     root: "Rover_base"
     tip: "Force_Sensor_l"
     ref_frame: constraint_ref_frame_tip
     priority: 0   
   - name: cart_pos_ctrl_right_arm
     type: cart
     root: "Rover_base"
     tip: "Hand_r"
     priority: 0
   - name: self_collision_avoidance
     type: jnt
     priority: 0
     joint_names: ["J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
                      "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l"]
   - name: keep_hands_parallel_ctrl
     type: cart
     root: "Hand_r"
     tip: "Hand_l"
     priority: 1
   - name: cart_pos_ctrl_left_arm
     type: cart
     root: "Rover_base"
     tip: "Hand_l"
     priority: 1
   - name: joint_pos_ctrl
     type: jnt
     priority: 2
     joint_names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
                   "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
                   "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
                   "J_Pan", "J_Tilt"]
   - name: joint_limit_avoidance
     type: jnt
     priority: 3
     joint_names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
                   "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
                   "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
                   "J_Pan", "J_Tilt"]
   - name: body_posture_ctrl
     type: cart
     root: "Rover_base"
     tip: "Chest"
     priority: 4
