# Configuration for wbc_ctrl_gui

wbc_task: aila_wbc

tasks:
  - name: cart_pos_ctrl_right_arm
    type: cart
    connect_output_to: 
       task: cart_pos_ctrl_right_proxy
       port: input
    connect_input_to:
       task: wbc
       port: pose_cart_pos_ctrl_right_arm
    controlled_in_frame: base_link
    controlled_frame_frame: Hand_r
    setpoint_frame: setpoint_hand_r
    translational_range: 3.0
    rotational_range: 6.28
  - name: joint_pos_ctrl
    type: jnt
    connect_output_to: 
       task: joint_pos_ctrl
       port: setpoint
    connect_input_to:
       task: aila_dispatcher
       port: all_joint_state
    limits:
       names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
               "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
               "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l", 
               "J_Pan", "J_Tilt"]
       elements: [{max: {position: 1.919862175, speed: 0.1, effort: 0.5}, min: {position: -1.919862175}}, # J_Foot
                  {max: {position: 2.705260337, speed: 0.1, effort: 0.5}, min: {position: 2.1816615625}}, # J_Knees
                  {max: {position: 2.705260337, speed: 0.1, effort: 0.5}, min: {position: 1.919862175 }}, # J_Hip
                  {max: {position: 1.04719755,  speed: 0.1, effort: 0.5}, min: {position: -1.04719755 }}, # J_Waist
                  {max: {position: 0.872664625, speed: 0.5, effort: 2.0}, min: {position: -1.74532925 }}, # J_Shoulder1_r
                  {max: {position: 1.483529862, speed: 0.5, effort: 2.0}, min: {position: -0.087266462}}, # J_Shoulder2_r
                  {max: {position: 1.919862175, speed: 0.5, effort: 2.0}, min: {position: -1.919862175}}, # J_UpperArm_r
                  {max: {position: 1.832595712, speed: 0.5, effort: 2.0}, min: {position: -0.087266462}}, # J_Elbow_r
                  {max: {position: 1.570796325, speed: 0.5, effort: 2.0}, min: {position: -1.919862175}}, # J_Forearm_r
                  {max: {position: 0.01,        speed: 0.5, effort: 2.0}, min: {position: -1.570796325}}, # J_Wrist1_r
                  {max: {position: 0.610865237, speed: 0.5, effort: 2.0}, min: {position: -0.261799387}}, # J_Wrist2_r
                  {max: {position: 1.74532925,  speed: 0.5, effort: 2.0}, min: {position: -0.872664625}}, # J_Shoulder1_l
                  {max: {position: 0.087266462, speed: 0.5, effort: 2.0}, min: {position: -1.483529862}}, # J_Shoulder2_l
                  {max: {position: 1.919862175, speed: 0.5, effort: 2.0}, min: {position: -1.919862175}}, # J_UpperArm_l
                  {max: {position: 0.087266462, speed: 0.5, effort: 2.0}, min: {position: -1.832595712}}, # J_Elbow_l
                  {max: {position: 1.570796325, speed: 0.5, effort: 2.0}, min: {position: -1.919862175}}, # J_Forearm_l
                  {max: {position: 0.01,       speed:  0.5, effort: 2.0}, min: {position: -1.570796325}}, # J_Wrist1_l
                  {max: {position: 0.261799387, speed: 0.5, effort: 2.0}, min: {position: -0.610865237}}, # J_Wrist2_l
                  {max: {position: 0.785398162, speed: 0.5, effort: 2.0}, min: {position: -0.6981317  }}, # J_Pan
                  {max: {position: 0.523598775, speed: 0.5, effort: 2.0}, min: {position: -1.04719755 }}] # J_Tilt
