# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen
image: alpine

include:
  - project: 'build_server/gitlab_ci_includes'
    file: 'api_publish.yml'
  - project: 'build_server/gitlab_ci_includes'
    file: 'software_catalogue.yml'
    
build_rock_18.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-wbc_ubuntu:18.04
  stage: build
  script:
    - aup --config
    - aup
    - amake orogen/wbc

build_rock_20.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-wbc_ubuntu:20.04
  stage: build
  script:
    - aup --config
    - aup
    - amake orogen/wbc

run_tests_18.04:
  image: d-reg.hb.dfki.de:5000/gitlab-ci/docker-wbc_ubuntu:18.04
  stage: test
  script:
  - aup --config
  - aup
  - amake orogen/wbc
  - gem install rake
  - aup & amake tools/orocos.rb
  - cd test
  - ruby test_wbc_velocity_task.rb

