--- name:default
# Name for each variable, e.g. joint names in case of joint space controller
field_names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
             "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
             "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
             "J_Pan", "J_Tilt"]

# Maximum control output (saturation). If one output value exceeds maximum, all other values will be scaled accordingly. Default is infinite.
initial_max_control_output:
  data: [0.05, 0.05, 0.05, 0.05, 
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
         0.1, 0.1]

# Maximum influence distance of the potential fields oer joint. For N joints, this vector has to have size N.
initial_influence_distance:
  data: [0.1, 0.05, 0.05, 0.1,
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,    
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
         0.05, 0.05]

# Order of the potential field. If M = 0 controlOutput = const, if M = 1, controlOutput ~ 1/d. If M = 2, controlOutput ~ 1/d^2 and so on.
order: 1

# Proportional gain.
initial_prop_gain:
  data: [0.1,0.1,0.1,0.1,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         0.1,0.1]


--- name:upper_limits

# Initial center of the potential fields. For N joints this has to have size N.
initial_pot_field_centers:
  names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
          "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
          "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
          "J_Pan", "J_Tilt"]
  elements: [{position: 1.91}, {position: 2.70}, {position: 2.70}, {position: 1.04},
             {position: 3.10}, {position: 1.51}, {position: 2.93}, {position: 2.00}, {position: 2.6}, {position: -0.01}, {position: 0.61}, 
             {position: 3.10}, {position: 0.10}, {position: 2.93}, {position: 0.35}, {position: 2.6}, {position: -0.01}, {position: 0.61},
             {position: 0.70}, {position: 0.52}]
