--- name:default
# Name for each variable, e.g. joint names in case of joint space controller
field_names: ["X", "Y", "Z", "rotZ", "rotY", "rotX"]

# Minimum control error (dead zone). If one value falls below minimum, it will be set to zero. Default is zero.
initial_dead_zone:
  data: [0,0,0,0,0,0]

# Maximum control output (saturation). If one output value exceeds maximum, all other values will be scaled accordingly. Default is infinite.
initial_max_control_output:
  data: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

# Proportional gain.
initial_prop_gain:
  data: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
