--- name:default
# Minimum control error (dead zone). If one value falls below minimum, it will be set to zero. Default is zero.
deadZone:
  data: []

# Joints used by this controller (ctrlOutput will be in this order).
jointNames: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
             "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
             "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
             "J_Pan", "J_Tilt"]

# Maximum control output (saturation). If one output value exceeds maximum, all other values will be scaled accordingly. Default is infinite.
maxControlOutput:
  data: [0.05, 0.05, 0.05, 0.05, 
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
         0.1, 0.1]

# Maximum influence distance of the potential fields oer joint. For N joints, this vector has to have size N.
maxInfluenceDistance:
  data: [0.1, 0.05, 0.05, 0.1,
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,    
         0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
         0.05, 0.05]

# Order of the potential field. If M = 0 controlOutput = const, if M = 1, controlOutput ~ 1/d. If M = 2, controlOutput ~ 1/d^2 and so on.
order: 1.0

# Proportional gain.
propGain:
  data: [0.1,0.1,0.1,0.1,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         0.1,0.1]


--- name:upper_limits

# Initial center of the potential fields. For N joints this has to have size N.
potFieldCenters:
  data: [1.91, 2.70, 2.70, 1.04,
         3.10, 1.51, 2.93, 2.00, 2.6, -0.01, 0.61, 
         3.10, 0.10, 2.93, 0.35, 2.6, -0.01, 0.61,
         0.70, 0.52]
