--- name:default

# Minimum control error (dead zone). If one value falls below minimum, it will be set to zero. Default is zero.
initial_dead_zone:
  data: [0,0,0,0, 
         0,0,0,0,0,0,0,
         0,0,0,0,0,0,0,
         0,0]

# Name for each variable, e.g. joint names in case of joint space controller
field_names: ["J_Foot", "J_Knees", "J_Hip", "J_Waist", 
             "J_Shoulder1_r", "J_Shoulder2_r", "J_UpperArm_r", "J_Elbow_r", "J_Forearm_r", "J_Wrist1_r", "J_Wrist2_r", 
             "J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l", "J_Wrist1_l", "J_Wrist2_l",
             "J_Pan", "J_Tilt"]

# Maximum control output (saturation). If one output value exceeds maximum, all other values will be scaled accordingly. Default is infinite.
initial_max_control_output:
  data: [0.5, 0.5, 0.5, 0.5,
         0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
         0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
         0.5, 0.5]

# Proportional gain.
initial_prop_gain:
  data: [0.1,0.1,0.1,0.1,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         1.0,1.0,1.0,1.0,1.0,1.0,1.0,
         0.1,0.1]
