# Configuration for wbc_ctrl_gui

wbc_task: wbc

tasks:
  - name: cart_pos_ctrl_right_arm
    type: cart
    connect_output_to: 
       task: cart_pos_ctrl_right_arm
       port: setpoint
    connect_input_to:
       task: wbc
       port: pose_cart_pos_ctrl_right_arm
    controlled_in_frame: Rover_base
    controlled_frame_frame: Hand_r
    setpoint_frame: setpoint_hand_r
    translational_range: 3.0
    rotational_range: 6.28
