--- name:rh5_single_leg
self_collision: false
realtime_calc: true
step_size: 0.001
control_mode: :PD_PLUS_FEEDFORWARD_TORQUE
p_gains_global: 1000
d_gains_global: 50
damping_global: 10.0
urdf_path: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/urdf/rh5_single_leg_fixed.urdf"  %>
initial_pose:
  position:
    data: [0,0,2]
  orientation:
    re: 1.0
    im: [0,0,0]
initial_state:
  names: ["LLHip1", "LLHip2", "LLHip3", "LLKnee", "LLAnkleRoll", "LLAnklePitch"]
  elements: [{position: 0.0,   speed: 0.0, effort: 0.6},   # LLHip1
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LLHip2
             {position: -0.35, speed: 0.0, effort: -0.7}, # LLHip3
             {position: 0.64,  speed: 0.0, effort: -9.7},  # LLKnee
             {position: 0.0,   speed: 0.0, effort: 0.3},   # LLAnkleRoll
             {position: -0.27, speed: 0.0, effort: 1.5}] # LLAnklePitch

--- name:rh5_legs
self_collision: false
realtime_calc: true
step_size: 0.001
control_mode: :PD_PLUS_FEEDFORWARD_TORQUE
p_gains_global: 1000
d_gains_global: 50
damping_global: 1
urdf_path: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/urdf/rh5_legs.urdf"  %>
imu_name: "IMU"
ft_sensor_names: ["LRAnkle_FT", "LLAnkle_FT"]
initial_pose:
  position:
    data: [0,0,0.89]
  orientation:
    re: 1.0
    im: [0,0,0]
initial_state:
  names: ["LLHip1", "LLHip2", "LLHip3", "LLKnee", "LLAnkleRoll", "LLAnklePitch",
          "LRHip1", "LRHip2", "LRHip3", "LRKnee", "LRAnkleRoll", "LRAnklePitch"]
  elements: [{position: 0.0,   speed: 0.0, effort: 0.6},   # LLHip1
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LLHip2
             {position: -0.35, speed: 0.0, effort: -0.7}, # LLHip3
             {position: 0.64,  speed: 0.0, effort: -9.7},  # LLKnee
             {position: 0.0,   speed: 0.0, effort: 0.3},   # LLAnkleRoll
             {position: -0.27, speed: 0.0, effort: 0.9}, # LLAnklePitch
             {position: 0.0,   speed: 0.0, effort: 0.6},   # LRHip1
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LRHip2
             {position: -0.35, speed: 0.0, effort: -0.7}, # LRHip3
             {position: 0.64,  speed: 0.0, effort: -9.7},  # LRKnee
             {position: 0.0,   speed: 0.0, effort: 0.3},   # LRAnkleRoll
             {position: -0.27, speed: 0.0, effort: 0.9}] # LRAnklePitch

--- name:rh5
self_collision: false
realtime_calc: true
step_size: 0.001
control_mode: :PD_PLUS_FEEDFORWARD_TORQUE
p_gains_global: 1000
d_gains_global: 50
damping_global: 1.0
urdf_path:  <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/models/robots/rh5/urdf/RH5.urdf" %>
imu_name: "IMU"
ft_sensor_names: ["LRAnkle_FT", "LLAnkle_FT"]
initial_pose:
  position:
    data: [0,0,0.89]
  orientation:
    re: 1.0
    im: [0,0,0]
initial_state:
  names: ["LLHip1", "LLHip2", "LLHip3", "LLKnee", "LLAnkleRoll", "LLAnklePitch",
          "LRHip1", "LRHip2", "LRHip3", "LRKnee", "LRAnkleRoll", "LRAnklePitch",
          "BodyPitch",
          "ALShoulder1", "ALShoulder2", "ARShoulder1", "ARShoulder2", "ALElbow", "ARElbow"]
  elements: [{position: 0.0,   speed: 0.0, effort: 0.0},   # LLHip1
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LLHip2
             {position: -0.33, speed: 0.0, effort: -0.0}, # LLHip3
             {position: 0.63,  speed: 0.0, effort: -10.00},  # LLKnee
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LLAnkleRoll
             {position: -0.3, speed: 0.0, effort: 0.0}, # LLAnklePitch
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LRHip1
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LRHip2
             {position: -0.33, speed: 0.0, effort: -0.00}, # LRHip3
             {position: 0.63,  speed: 0.0, effort: -10.0},  # LRKnee
             {position: 0.0,   speed: 0.0, effort: 0.0},   # LRAnkleRoll
             {position: -0.3, speed: 0.0, effort: 0.0}, # LRAnklePitch
             {position: 0.2, speed: 0.0, effort: 0.0}, # BodyPitch
             {position: -0.3, speed: 0.0, effort: 0}, # ALShoulder1
             {position: 0.5, speed: 0.0, effort: 0.0}, # ALShoulder2
             {position: 0.3, speed: 0.0, effort: 0.0}, # ARShoulder1
             {position: -0.5, speed: 0.0, effort: -0.0}, # ARShoulder2
             {position: -0.3, speed: 0.0, effort: -0.0}, # ALElbow
             {position: 0.3, speed: 0.0, effort: 0.0}] # ARElbow

--- name:rh5v2
self_collision: false
realtime_calc: true
step_size: 0.001
control_mode: :PD_PLUS_FEEDFORWARD_TORQUE
p_gains_global: 2000
d_gains_global: 50
damping_global: 1.0
urdf_path: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/bundles/wbc_examples/config/models/rh5v2/urdf/RH5v2.urdf"  %>
initial_pose:
  position:
    data: [0,0,0.89]
  orientation:
    re: 1.0
    im: [0,0,0]
initial_state:
  names: ["HeadPitch", "HeadRoll", "HeadYaw",
          "BodyPitch", "BodyRoll", "BodyYaw",
          "ALShoulder1", "ALShoulder2", "ALShoulder3", "ALElbow", "ALWristRoll", "ALWristPitch", "ALWristYaw",
          "ARShoulder1", "ARShoulder2", "ARShoulder3", "ARElbow", "ARWristRoll", "ARWristPitch", "ARWristYaw"]
  elements: [{position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # HeadPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # HeadRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # HeadYaw
             {position: 0.1, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # BodyPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # BodyRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # BodyYaw
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALShoulder1
             {position: 1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALShoulder2
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALShoulder3
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALElbow
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALWristRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALWristPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALWristYaw
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARShoulder1
             {position: 1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARShoulder2
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARShoulder3
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARElbow
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARWristRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARWristPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}] # ARWristYaw
