--- name:default
# Perform numerical integration on the solver output, e.g. if output is acceleration type, integrate twice to get velocity and acceleration
integrate: true
# Type of QP solver used. Can be one of ['qpoases','qpswift','eiquadprog']
qp_solver: eiquadprog
# This value is added to the diagonal of the Hessian matrix inside the QP to reduce the risk of infeasibility
hessian_regularizer: 1e-8
# Use reduced QP. If true, torques will be eliminated from the QP by expressing them as function of qdd and f_ext.
reduced: true

--- name:rh5_single_leg
# Configuration of the robot model. See wbc/core/RobotModelConfig.hpp for details.
robot_model:
  file: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/urdf/rh5_single_leg.urdf" %>
  submechanism_file: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/hyrodyn/rh5_single_leg.yml" %>
  floating_base: false
  type: hyrodyn

--- name:rh5_legs
# Configuration of the robot model. See wbc/core/RobotModelConfig.hpp for details.
robot_model:
    file: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/urdf/rh5_legs.urdf" %>
    submechanism_file: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/hyrodyn/rh5_legs.yml" %>
    floating_base: true
    contact_points:
        names: ["FL_SupportCenter", "FR_SupportCenter"]
        elements:
            - mu: 0.5
              active: 1
            - mu: 0.5
              active: 1

--- name:rh5
# Configuration of the robot model. See wbc/core/RobotModelConfig.hpp for details.
robot_model:
    file: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/urdf/rh5.urdf" %>
    submechanism_file: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5/hyrodyn/rh5.yml" %>
    floating_base: true
    type: hyrodyn
    contact_points:
        names: ["FL_SupportCenter", "FR_SupportCenter"]
        elements:
            - mu: 0.6
              active: 1
              wx: 0.2
              wy: 0.08
            - mu: 0.6
              active: 1
              wx: 0.2
              wy: 0.08

--- name:single_leg_ctrl
# Configuration of constraints. The WbcVelocityTask will dynamically create the following input ports for each constraint:
#              Cartesian constraints:
#                  Reference Input (/base/samples/RigidBodyState):         ref_<constraint_name>
#                  Weights (/base/VectorXd):                               weight_<constraint_name>
#                  Activation function (double):                           activation_<constraint_name>
#                  Constraint pose output (/base/samples/RigidBodyState):  state_<constraint_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
#              Joint Space constraints:
#                  Reference Input (/base/samples/Joints):                 ref_<task_name>
#                  Weights (/base/VectorXd):                               weight_<task_name>
#                  Activation function (double):                           activation_<task_name>
#                  Current joint state output (base/samples/Joints):       state_<task_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
wbc_config:
    - name: "cart_position_ctrl"
      priority: 0
      type: cart
      root: "RH5_Root_Link"
      tip:  "LLAnklePitch_Link"
      ref_frame: "RH5_Root_Link"
      activation: 1.0
      weights: [1,1,1,1,1,1]

--- name:com_ctrl
# Configuration of constraints. The WbcVelocityTask will dynamically create the following input ports for each constraint:
#              Cartesian constraints:
#                  Reference Input (/base/samples/RigidBodyState):         ref_<constraint_name>
#                  Weights (/base/VectorXd):                               weight_<constraint_name>
#                  Activation function (double):                           activation_<constraint_name>
#                  Constraint pose output (/base/samples/RigidBodyState):  state_<constraint_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
#              Joint Space constraints:
#                  Reference Input (/base/samples/Joints):                 ref_<task_name>
#                  Weights (/base/VectorXd):                               weight_<task_name>
#                  Activation function (double):                           activation_<task_name>
#                  Current joint state output (base/samples/Joints):       state_<task_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
wbc_config:
- name: "com_ctrl"
  priority: 0
  type: com
  activation: 1.0
  weights: [1,1,1]
  # root: "world"
  # tip:  "RH5_Root_Link"
  # ref_frame: "world"
- name: "joint_ctrl"
  priority: 0
  activation: 1.0
  type: jnt
  joint_names: ["HeadPitch", "HeadRoll", "HeadYaw",
                "BodyPitch", "BodyRoll", "BodyYaw",
                "LLHip1", "LLHip2", "LLHip3", "LLKnee", "LLAnkleRoll", "LLAnklePitch",
                "LRHip1", "LRHip2", "LRHip3", "LRKnee", "LRAnkleRoll", "LRAnklePitch",
                "ALShoulder1", "ALShoulder2", "ALShoulder3", "ALElbow", "ALWristRoll", "ALWristPitch", "ALWristYaw",
                "ARShoulder1", "ARShoulder2", "ARShoulder3", "ARElbow", "ARWristRoll", "ARWristPitch", "ARWristYaw"]
  weights: [1-2,1-2,1-2,
            1-2,1-2,1-2,
            1e-8,1e-8,1e-8,1e-8,1e-8,1e-8,
            1e-8,1e-8,1e-8,1e-8,1e-8,1e-8,
            1e-8,1e-8,1e-8,1e-8,1e-8,1e-8,1e-8,
            1e-8,1e-8,1e-8,1e-8,1e-8,1e-8,1e-8]
