--- name:default
# Type of activation function used. See ctrl_lib/ActivationFunction.hpp for details.
activation_function:
  threshold: 0.5
  type: :LINEAR_ACTIVATION
# Unique name for each variable, e.g. joint names in case of a joint space controller.
field_names: ["kuka_lbr_r_joint_1",
              "kuka_lbr_r_joint_2",
              "kuka_lbr_r_joint_3",
              "kuka_lbr_r_joint_4",
              "kuka_lbr_r_joint_5",
              "kuka_lbr_r_joint_6",
              "kuka_lbr_r_joint_7"]
# Default influence distance. Has to be > 0!
influence_distance:
    data: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
# Initial maximum control output (saturation). If one output value exceeds maximum, all other
# values will be scaled accordingly. Size has to be same as field_names.
max_control_output:
  data: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
# Initial proportional gain. Size has to be the same as size of field_names.
p_gain:
  data: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
# Initial centers of the potential fields. Size has to be either empty or same as size of field_names. If empty the task will be wait for input from port
joint_limits:
  names: ["kuka_lbr_r_joint_1",
          "kuka_lbr_r_joint_2",
          "kuka_lbr_r_joint_3",
          "kuka_lbr_r_joint_4",
          "kuka_lbr_r_joint_5",
          "kuka_lbr_r_joint_6",
          "kuka_lbr_r_joint_7"]
  elements: [{max: {position: 2.96705972839}, min: {position: -2.96705972839}}, # kuka_lbr_r_joint_1
             {max: {position: 2.09439510239}, min: {position: -2.09439510239}}, # kuka_lbr_r_joint_2
             {max: {position: 2.96705972839}, min: {position: -2.96705972839}}, # kuka_lbr_r_joint_3
             {max: {position: 2.09439510239}, min: {position: -2.09439510239}}, # kuka_lbr_r_joint_4
             {max: {position: 2.96705972839}, min: {position: -2.96705972839}}, # kuka_lbr_r_joint_5
             {max: {position: 2.09439510239}, min: {position: -2.09439510239}}, # kuka_lbr_r_joint_6
             {max: {position: 3.05432619099}, min: {position: -3.05432619099}}] # kuka_lbr_l_joint_7
