--- name:default
# no documentation available for this property
base_frame: "kuka_lbr_base"
# Add multiple robot and/or object models.
robot_models:
    - file: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/orogen/wbc/examples/models/kuka_lbr.urdf" %>
# Optionally set the order of joints here. If empty, order will be as in the robot model.
joint_names: ["kuka_lbr_r_joint_1","kuka_lbr_r_joint_2","kuka_lbr_r_joint_3","kuka_lbr_r_joint_4","kuka_lbr_r_joint_5","kuka_lbr_r_joint_6","kuka_lbr_r_joint_7"]
# Joint weights control the contribution of each individual joint to the task solution. A zero means here that the joint is not used at all.
#              Size has to be same as joint_names
initial_joint_weights:
  data: [1,1,1,1,1,1,1]

--- name:cart_control_with_joint_limits
# Configuration of constraints. The WbcVelocityTask will dynamically create the following input ports for each constraint:
#              Cartesian constraints:
#                  Reference Input (/base/samples/RigidBodyState):         ref_<constraint_name>
#                  Weights (/base/VectorXd):                               weight_<constraint_name>
#                  Activation function (double):                           activation_<constraint_name>
#                  Constraint pose output (/base/samples/RigidBodyState):  state_<constraint_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
#              Joint Space constraints:
#                  Reference Input (/base/samples/Joints):                 ref_<task_name>
#                  Weights (/base/VectorXd):                               weight_<task_name>
#                  Activation function (double):                           activation_<task_name>
#                  Current joint state output (base/samples/Joints):       state_<task_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
wbc_config:
    - name: "cart_position_ctrl_right"
      priority: 0
      type: cart
      root: "kuka_lbr_base"
      tip:  "kuka_lbr_r_tcp"
      ref_frame: "kuka_lbr_base"
      activation: 1.0
      weights: [1,1,1,1,1,1]

    - name: "joint_limit_avoidance"
      priority: 1
      type: jnt
      activation: 1.0
      joint_names: ["kuka_lbr_r_joint_1","kuka_lbr_r_joint_2","kuka_lbr_r_joint_3","kuka_lbr_r_joint_4","kuka_lbr_r_joint_5","kuka_lbr_r_joint_6","kuka_lbr_r_joint_7"]
      weights: [1,1,1,1,1,1,1]


--- name:position_force_control
# Configuration of constraints. The WbcVelocityTask will dynamically create the following input ports for each constraint:
#              Cartesian constraints:
#                  Reference Input (/base/samples/RigidBodyState):         ref_<constraint_name>
#                  Weights (/base/VectorXd):                               weight_<constraint_name>
#                  Activation function (double):                           activation_<constraint_name>
#                  Constraint pose output (/base/samples/RigidBodyState):  state_<constraint_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
#              Joint Space constraints:
#                  Reference Input (/base/samples/Joints):                 ref_<task_name>
#                  Weights (/base/VectorXd):                               weight_<task_name>
#                  Activation function (double):                           activation_<task_name>
#                  Current joint state output (base/samples/Joints):       state_<task_name>
#                  Constraint output port (wbc/Constraint)                 constraint_<constraint_name>
wbc_config:
    - name: "cart_position_ctrl_right"
      priority: 0
      type: cart
      root: "kuka_lbr_base"
      tip:  "kuka_lbr_r_tcp"
      ref_frame: "kuka_lbr_base"
      activation: 1.0
      weights: [1,1,1,1,1,1]

    - name: "cart_force_ctrl_right"
      priority: 0
      type: cart
      root: "kuka_lbr_base"
      tip:  "kuka_lbr_r_tcp"
      ref_frame: "kuka_lbr_r_tcp"
      activation: 1.0
      weights: [1,1,1,1,1,1]
