--- name:default
# Precision for eigenvalue inversion. Required to ensure numerical stability. Inverse of an Eigenvalue smaller than this will be set to zero
epsilon: 1.0e-09
# Maximum joint velocity (in rad/sec) for each joint. If empty, infinite output will be allowed. If not empty, size has to be same as number of joints
max_solver_output:
  data: [0.1,0.1,0.1,0.1,0.1,0.1,0.1]
# Maximum allowed norm of the solution. An infinite value will provide the most accurate, but eventually unbounded solution. A lower value will prevent unbounded
#             control velocities near singular configurations.
norm_max: 10.0
# Joint weights control the contribution of each individual joint to the task solution. A zero means here that the joint is not used at all.
#              Size has to be same as joint_names
initial_joint_weights:
  data: [1,1,1,1,1,1,1]
