--- name:rh5v2
self_collision: false
realtime_calc: true
step_size: 0.001
control_mode: :PD_PLUS_FEEDFORWARD_TORQUE
p_gains_global: 1000
d_gains_global: 50
damping_global: 10.0
urdf_path: <%= "#{ENV['AUTOPROJ_CURRENT_ROOT']}/control/wbc/models/rh5v2/raisim/rh5v2.urdf"  %>
initial_pose:
  position:
    data: [0,0,0.89]
  orientation:
    re: 1.0
    im: [0,0,0]
initial_state:
  names: ["HeadPitch", "HeadRoll", "HeadYaw",
          "BodyPitch", "BodyRoll", "BodyYaw",
          "ALShoulder1", "ALShoulder2", "ALShoulder3", "ALElbow", "ALWristRoll", "ALWristPitch", "ALWristYaw",
          "ARShoulder1", "ARShoulder2", "ARShoulder3", "ARElbow", "ARWristRoll", "ARWristPitch", "ARWristYaw"]
  elements: [{position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # HeadPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # HeadRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # HeadYaw
             {position: 0.1, speed: 0.0, raw: 0.0, effort: -60.0, acceleration: 0.0}, # BodyPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 11.0, acceleration: 0.0}, # BodyRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 1.0, acceleration: 0.0}, # BodyYaw
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALShoulder1
             {position: 1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALShoulder2
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALShoulder3
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALElbow
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALWristRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALWristPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ALWristYaw
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARShoulder1
             {position: 1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARShoulder2
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARShoulder3
             {position: -1.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARElbow
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARWristRoll
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}, # ARWristPitch
             {position: 0.0, speed: 0.0, raw: 0.0, effort: 0.0, acceleration: 0.0}] # ARWristYaw
