--- name:default
# Behaviour at the position limits (only reflexxes TypeIV!!!). Can be one of the following:
#   - POSITIONAL_LIMITS_IGNORE: Positional limits are completely ignored
#   - POSITIONAL_LIMITS_ERROR_MSG_ONLY: Component will go into error state if target is out of bounds
#   - POSITIONAL_LIMITS_ACTIVELY_PREVENT: Reflexxes will provide a smooth transition at the bounds and avoid exceeding them
# See reflexxes/RMLFlags.h for further details.
positional_limits_behavior: :POSITIONAL_LIMITS_IGNORE
# Synchronization behavior between different elements. Can be one of PHASE_SYNCHRONIZATION_IF_POSSIBLE, ONLY_TIME_SYNCHRONIZATION,
# ONLY_PHASE_SYNCHRONIZATION and NO_SYNCHRONIZATION. See reflexxes/RMLFlags.h for details.
synchronization_behavior: :PHASE_SYNCHRONIZATION_IF_POSSIBLE

--- name:arm_ctrl
# Motion constraints that define the properties of the output trajectory that is sent on the command-port.
# These include the maximum/minimum position (only Reflexxes TypeIV), maximum maximum speed, maximum acceleration and maximum jerk
# (derivative of acceleration, only Reflexxes TypeIV).
motion_constraints:
  names: ["x", "y", "z", "rot_z", "rot_y", "rot_x"]
  elements: [{max: {position: 1.0, speed: 0.25, acceleration: 2.0}, min: {position: -1.0}, max_jerk: 1.0},
             {max: {position: 1.0, speed: 0.25, acceleration: 2.0}, min: {position: -1.0}, max_jerk: 1.0},
             {max: {position: 1.0, speed: 0.25, acceleration: 2.0}, min: {position: -1.0}, max_jerk: 1.0},
             {max: {position: 1.0, speed: 0.25, acceleration: 2.0}, min: {position: -1.0}, max_jerk: 1.0},
             {max: {position: 1.0, speed: 0.25, acceleration: 2.0}, min: {position: -1.0}, max_jerk: 1.0},
             {max: {position: 1.0, speed: 0.25, acceleration: 2.0}, min: {position: -1.0}, max_jerk: 1.0}]
