--- name:recupera_exo
# no documentation available for this property
initial_joint_state:
  names: ["left_leg_hip_task_space_roll_joint", "left_leg_hip_task_space_pitch_joint", "left_leg_hip_task_space_yaw_joint", "left_leg_leg_EE_joint0", "left_leg_feet_task_space_roll_joint", "left_leg_feet_task_space_pitch_joint", "left_leg_feet_task_space_yaw_joint",
          "right_leg_hip_task_space_roll_joint", "right_leg_hip_task_space_pitch_joint", "right_leg_hip_task_space_yaw_joint", "right_leg_leg_EE_joint0", "right_leg_feet_task_space_roll_joint", "right_leg_feet_task_space_pitch_joint", "right_leg_feet_task_space_yaw_joint"]
  elements: [{position: 0.0}, # left_leg_hip_task_space_roll_joint
             {position: 0.0}, # left_leg_hip_task_space_pitch_joint
             {position: 0.0}, # left_leg_hip_task_space_yaw_joint
             {position: 0.0}, # left_leg_leg_EE_joint0
             {position: 0.0}, # left_leg_feet_task_space_roll_joint
             {position: 0.0}, # left_leg_feet_task_space_pitch_joint
             {position: 0.0}, # left_leg_feet_task_space_yaw_joint
             {position: 0.0}, # right_leg_hip_task_space_roll_joint
             {position: 0.0}, # right_leg_hip_task_space_pitch_joint
             {position: 0.0}, # right_leg_hip_task_space_yaw_joint
             {position: 0.0}, # right_leg_leg_EE_joint0
             {position: 0.0}, # right_leg_feet_task_space_roll_joint
             {position: 0.0}, # right_leg_feet_task_space_pitch_joint
             {position: 0.0}] # right_leg_feet_task_space_yaw_joint

# no documentation available for this property
noise_std_dev: 0

--- name:recupera_exo_hybrid
# no documentation available for this property
initial_joint_state:
  names: ["left_leg_hip_task_space_roll_joint",
          "left_leg_hip_task_space_pitch_joint",
          "left_leg_hip_task_space_yaw_joint",
          "left_leg_hip_end_effector_x_joint",
          "left_leg_hip_end_effector_y_joint",
          "left_leg_hip_end_effector_z_joint",
          "left_leg_hip_motor_0_joint",
          "left_leg_hip_lever_1_roll_joint",
          "left_leg_hip_lever_1_pitch_joint",
          "left_leg_hip_lever_1_cut_joint",
          "left_leg_hip_lever_2_roll_joint",
          "left_leg_hip_lever_2_pitch_joint",
          "left_leg_hip_lever_2_cut_joint",
          "left_leg_hip_motor_1_joint",
          "left_leg_hip_lever_3_roll_joint",
          "left_leg_hip_lever_3_pitch_joint",
          "left_leg_hip_lever_3_cut_joint",
          "left_leg_hip_lever_4_roll_joint",
          "left_leg_hip_lever_4_pitch_joint",
          "left_leg_hip_lever_4_cut_joint",
          "left_leg_hip_motor_2_joint",
          "left_leg_hip_lever_5_roll_joint",
          "left_leg_hip_lever_5_pitch_joint",
          "left_leg_hip_lever_5_cut_joint",
          "left_leg_hip_lever_6_roll_joint",
          "left_leg_hip_lever_6_pitch_joint",
          "left_leg_hip_lever_6_cut_joint",

          "left_leg_leg_EE_joint0",
          "left_leg_leg_seat_joint",
          "left_leg_leg_seat_lever_joint",
          "left_leg_leg_seat_clamping_joint",
          "left_leg_leg_support_joint",
          "left_leg_leg_support_lever_joint",
          "left_leg_leg_support_clamping_joint",

          "left_leg_feet_task_space_roll_joint",
          "left_leg_feet_task_space_pitch_joint",
          "left_leg_feet_task_space_yaw_joint",
          "left_leg_feet_end_effector_x_joint",
          "left_leg_feet_end_effector_y_joint",
          "left_leg_feet_end_effector_z_joint",
          "left_leg_feet_motor_0_joint",
          "left_leg_feet_lever_1_roll_joint",
          "left_leg_feet_lever_1_pitch_joint",
          "left_leg_feet_lever_1_cut_joint",
          "left_leg_feet_lever_2_roll_joint",
          "left_leg_feet_lever_2_pitch_joint",
          "left_leg_feet_lever_2_cut_joint",
          "left_leg_feet_motor_1_joint",
          "left_leg_feet_lever_3_roll_joint",
          "left_leg_feet_lever_3_pitch_joint",
          "left_leg_feet_lever_3_cut_joint",
          "left_leg_feet_lever_4_roll_joint",
          "left_leg_feet_lever_4_pitch_joint",
          "left_leg_feet_lever_4_cut_joint",
          "left_leg_feet_motor_2_joint",
          "left_leg_feet_lever_5_roll_joint",
          "left_leg_feet_lever_5_pitch_joint",
          "left_leg_feet_lever_5_cut_joint",
          "left_leg_feet_lever_6_roll_joint",
          "left_leg_feet_lever_6_pitch_joint",
          "left_leg_feet_lever_6_cut_joint",

          "right_leg_hip_task_space_roll_joint",
          "right_leg_hip_task_space_pitch_joint",
          "right_leg_hip_task_space_yaw_joint",
          "right_leg_hip_end_effector_x_joint",
          "right_leg_hip_end_effector_y_joint",
          "right_leg_hip_end_effector_z_joint",
          "right_leg_hip_motor_0_joint",
          "right_leg_hip_lever_1_roll_joint",
          "right_leg_hip_lever_1_pitch_joint",
          "right_leg_hip_lever_1_cut_joint",
          "right_leg_hip_lever_2_roll_joint",
          "right_leg_hip_lever_2_pitch_joint",
          "right_leg_hip_lever_2_cut_joint",
          "right_leg_hip_motor_1_joint",
          "right_leg_hip_lever_3_roll_joint",
          "right_leg_hip_lever_3_pitch_joint",
          "right_leg_hip_lever_3_cut_joint",
          "right_leg_hip_lever_4_roll_joint",
          "right_leg_hip_lever_4_pitch_joint",
          "right_leg_hip_lever_4_cut_joint",
          "right_leg_hip_motor_2_joint",
          "right_leg_hip_lever_5_roll_joint",
          "right_leg_hip_lever_5_pitch_joint",
          "right_leg_hip_lever_5_cut_joint",
          "right_leg_hip_lever_6_roll_joint",
          "right_leg_hip_lever_6_pitch_joint",
          "right_leg_hip_lever_6_cut_joint",

          "right_leg_leg_EE_joint0",
          "right_leg_leg_seat_joint",
          "right_leg_leg_seat_lever_joint",
          "right_leg_leg_seat_clamping_joint",
          "right_leg_leg_support_joint",
          "right_leg_leg_support_lever_joint",
          "right_leg_leg_support_clamping_joint",

          "right_leg_feet_task_space_roll_joint",
          "right_leg_feet_task_space_pitch_joint",
          "right_leg_feet_task_space_yaw_joint",
          "right_leg_feet_end_effector_x_joint",
          "right_leg_feet_end_effector_y_joint",
          "right_leg_feet_end_effector_z_joint",
          "right_leg_feet_motor_0_joint",
          "right_leg_feet_lever_1_roll_joint",
          "right_leg_feet_lever_1_pitch_joint",
          "right_leg_feet_lever_1_cut_joint",
          "right_leg_feet_lever_2_roll_joint",
          "right_leg_feet_lever_2_pitch_joint",
          "right_leg_feet_lever_2_cut_joint",
          "right_leg_feet_motor_1_joint",
          "right_leg_feet_lever_3_roll_joint",
          "right_leg_feet_lever_3_pitch_joint",
          "right_leg_feet_lever_3_cut_joint",
          "right_leg_feet_lever_4_roll_joint",
          "right_leg_feet_lever_4_pitch_joint",
          "right_leg_feet_lever_4_cut_joint",
          "right_leg_feet_motor_2_joint",
          "right_leg_feet_lever_5_roll_joint",
          "right_leg_feet_lever_5_pitch_joint",
          "right_leg_feet_lever_5_cut_joint",
          "right_leg_feet_lever_6_roll_joint",
          "right_leg_feet_lever_6_pitch_joint",
          "right_leg_feet_lever_6_cut_joint"]

  elements: [{position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},

             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0},
             {position: 0.0}]
# no documentation available for this property
noise_std_dev: 1e-4
