--- name:recupera_exo
# no documentation available for this property
initial_joint_state:
  names: ["left_leg_hip_task_space_roll_joint", "left_leg_hip_task_space_pitch_joint", "left_leg_hip_task_space_yaw_joint", "left_leg_leg_EE_joint0", "left_leg_feet_task_space_roll_joint", "left_leg_feet_task_space_pitch_joint", "left_leg_feet_task_space_yaw_joint",
          "right_leg_hip_task_space_roll_joint", "right_leg_hip_task_space_pitch_joint", "right_leg_hip_task_space_yaw_joint", "right_leg_leg_EE_joint0", "right_leg_feet_task_space_roll_joint", "right_leg_feet_task_space_pitch_joint", "right_leg_feet_task_space_yaw_joint"]
  elements: [{position: 0.0}, # left_leg_hip_task_space_roll_joint
             {position: 0.0}, # left_leg_hip_task_space_pitch_joint
             {position: 0.0}, # left_leg_hip_task_space_yaw_joint
             {position: 0.0}, # left_leg_leg_EE_joint0
             {position: 0.0}, # left_leg_feet_task_space_roll_joint
             {position: 0.0}, # left_leg_feet_task_space_pitch_joint
             {position: 0.0}, # left_leg_feet_task_space_yaw_joint
             {position: 0.0}, # right_leg_hip_task_space_roll_joint
             {position: 0.0}, # right_leg_hip_task_space_pitch_joint
             {position: 0.0}, # right_leg_hip_task_space_yaw_joint
             {position: 0.0}, # right_leg_leg_EE_joint0
             {position: 0.0}, # right_leg_feet_task_space_roll_joint
             {position: 0.0}, # right_leg_feet_task_space_pitch_joint
             {position: 0.0}] # right_leg_feet_task_space_yaw_joint

# no documentation available for this property
noise_std_dev: 0

--- name:recupera_exo_hybrid
# no documentation available for this property
initial_joint_state:
  names: ["left_leg_hip_task_space_roll_joint",
          "left_leg_hip_task_space_pitch_joint",
          "left_leg_hip_task_space_yaw_joint",
          "left_leg_hip_end_effector_x_joint",
          "left_leg_hip_end_effector_y_joint",
          "left_leg_hip_end_effector_z_joint",
          "left_leg_hip_motor_0_joint",
          "left_leg_hip_lever_1_roll_joint",
          "left_leg_hip_lever_1_pitch_joint",
          "left_leg_hip_lever_1_cut_joint",
          "left_leg_hip_lever_2_roll_joint",
          "left_leg_hip_lever_2_pitch_joint",
          "left_leg_hip_lever_2_cut_joint",
          "left_leg_hip_motor_1_joint",
          "left_leg_hip_lever_3_roll_joint",
          "left_leg_hip_lever_3_pitch_joint",
          "left_leg_hip_lever_3_cut_joint",
          "left_leg_hip_lever_4_roll_joint",
          "left_leg_hip_lever_4_pitch_joint",
          "left_leg_hip_lever_4_cut_joint",
          "left_leg_hip_motor_2_joint",
          "left_leg_hip_lever_5_roll_joint",
          "left_leg_hip_lever_5_pitch_joint",
          "left_leg_hip_lever_5_cut_joint",
          "left_leg_hip_lever_6_roll_joint",
          "left_leg_hip_lever_6_pitch_joint",
          "left_leg_hip_lever_6_cut_joint",

          "left_leg_leg_EE_joint0",
          "left_leg_leg_seat_joint",
          "left_leg_leg_seat_lever_joint",
          "left_leg_leg_seat_clamping_joint",
          "left_leg_leg_support_joint",
          "left_leg_leg_support_lever_joint",
          "left_leg_leg_support_clamping_joint",

          "left_leg_feet_task_space_roll_joint",
          "left_leg_feet_task_space_pitch_joint",
          "left_leg_feet_task_space_yaw_joint",
          "left_leg_feet_end_effector_x_joint",
          "left_leg_feet_end_effector_y_joint",
          "left_leg_feet_end_effector_z_joint",
          "left_leg_feet_motor_0_joint",
          "left_leg_feet_lever_1_roll_joint",
          "left_leg_feet_lever_1_pitch_joint",
          "left_leg_feet_lever_1_cut_joint",
          "left_leg_feet_lever_2_roll_joint",
          "left_leg_feet_lever_2_pitch_joint",
          "left_leg_feet_lever_2_cut_joint",
          "left_leg_feet_motor_1_joint",
          "left_leg_feet_lever_3_roll_joint",
          "left_leg_feet_lever_3_pitch_joint",
          "left_leg_feet_lever_3_cut_joint",
          "left_leg_feet_lever_4_roll_joint",
          "left_leg_feet_lever_4_pitch_joint",
          "left_leg_feet_lever_4_cut_joint",
          "left_leg_feet_motor_2_joint",
          "left_leg_feet_lever_5_roll_joint",
          "left_leg_feet_lever_5_pitch_joint",
          "left_leg_feet_lever_5_cut_joint",
          "left_leg_feet_lever_6_roll_joint",
          "left_leg_feet_lever_6_pitch_joint",
          "left_leg_feet_lever_6_cut_joint",

          "right_leg_hip_task_space_roll_joint",
          "right_leg_hip_task_space_pitch_joint",
          "right_leg_hip_task_space_yaw_joint",
          "right_leg_hip_end_effector_x_joint",
          "right_leg_hip_end_effector_y_joint",
          "right_leg_hip_end_effector_z_joint",
          "right_leg_hip_motor_0_joint",
          "right_leg_hip_lever_1_roll_joint",
          "right_leg_hip_lever_1_pitch_joint",
          "right_leg_hip_lever_1_cut_joint",
          "right_leg_hip_lever_2_roll_joint",
          "right_leg_hip_lever_2_pitch_joint",
          "right_leg_hip_lever_2_cut_joint",
          "right_leg_hip_motor_1_joint",
          "right_leg_hip_lever_3_roll_joint",
          "right_leg_hip_lever_3_pitch_joint",
          "right_leg_hip_lever_3_cut_joint",
          "right_leg_hip_lever_4_roll_joint",
          "right_leg_hip_lever_4_pitch_joint",
          "right_leg_hip_lever_4_cut_joint",
          "right_leg_hip_motor_2_joint",
          "right_leg_hip_lever_5_roll_joint",
          "right_leg_hip_lever_5_pitch_joint",
          "right_leg_hip_lever_5_cut_joint",
          "right_leg_hip_lever_6_roll_joint",
          "right_leg_hip_lever_6_pitch_joint",
          "right_leg_hip_lever_6_cut_joint",

          "right_leg_leg_EE_joint0",
          "right_leg_leg_seat_joint",
          "right_leg_leg_seat_lever_joint",
          "right_leg_leg_seat_clamping_joint",
          "right_leg_leg_support_joint",
          "right_leg_leg_support_lever_joint",
          "right_leg_leg_support_clamping_joint",

          "right_leg_feet_task_space_roll_joint",
          "right_leg_feet_task_space_pitch_joint",
          "right_leg_feet_task_space_yaw_joint",
          "right_leg_feet_end_effector_x_joint",
          "right_leg_feet_end_effector_y_joint",
          "right_leg_feet_end_effector_z_joint",
          "right_leg_feet_motor_0_joint",
          "right_leg_feet_lever_1_roll_joint",
          "right_leg_feet_lever_1_pitch_joint",
          "right_leg_feet_lever_1_cut_joint",
          "right_leg_feet_lever_2_roll_joint",
          "right_leg_feet_lever_2_pitch_joint",
          "right_leg_feet_lever_2_cut_joint",
          "right_leg_feet_motor_1_joint",
          "right_leg_feet_lever_3_roll_joint",
          "right_leg_feet_lever_3_pitch_joint",
          "right_leg_feet_lever_3_cut_joint",
          "right_leg_feet_lever_4_roll_joint",
          "right_leg_feet_lever_4_pitch_joint",
          "right_leg_feet_lever_4_cut_joint",
          "right_leg_feet_motor_2_joint",
          "right_leg_feet_lever_5_roll_joint",
          "right_leg_feet_lever_5_pitch_joint",
          "right_leg_feet_lever_5_cut_joint",
          "right_leg_feet_lever_6_roll_joint",
          "right_leg_feet_lever_6_pitch_joint",
          "right_leg_feet_lever_6_cut_joint"]

  elements: [{position: 0.00019367919948301795},
             {position: -0.00016355790212381225},
             {position: -0.0004027767772149931},
             {position: -6.443183377210856e-08},
             {position: -2.2721125675752214e-08},
             {position: -1.0648354342257531e-07},
             {position: 2.6362753814073302e-05},
             {position: 0.00012737240758705715},
             {position: -2.7258291195048796e-05},
             {position: 0.0},
             {position: -0.00012908632501817886},
             {position: -2.7299398121805424e-05},
             {position: 0.0},
             {position: 0.0003507765272281711},
             {position: 1.0439672192849354e-05},
             {position: -0.0003517762946888987},
             {position: 0.0},
             {position: -1.0557700699590373e-05},
             {position: -0.0003517765702450858},
             {position: 0.0},
             {position: 0.00032058538397795926},
             {position: 0.0001393787920472508},
             {position: -0.00032235467753746055},
             {position: 0.0},
             {position: -0.00014123487983328526},
             {position: -0.0003224038925563977},
             {position: 0.0},
             {position: -0.00027676337431289824},
             {position: 0.00114240715995656},
             {position: -0.0023746653631632167},
             {position: 0.0012322582032066622},
             {position: -0.0006295743112489508},
             {position: 0.0022568559439310725},
             {position: -0.0016272816326821215},
             {position: -0.0009217104683638859},
             {position: -0.00024198480851800425},
             {position: 0.0002394893167033987},
             {position: -6.798532317476721e-08},
             {position: -2.315494501409162e-07},
             {position: -5.4520067427611295e-08},
             {position: -0.00033565191237847},
             {position: 0.00021563497592034722},
             {position: 0.0003364599730622762},
             {position: 0.0},
             {position: -0.00021231934793260123},
             {position: 0.0003363289429438545},
             {position: 0.0},
             {position: -0.0006914580126690407},
             {position: -0.00011826621864693115},
             {position: 0.0006888492866156028},
             {position: 0.0},
             {position: 0.00011666000759280397},
             {position: 0.0006888098649358468},
             {position: 0.0},
             {position: 0.0006122963820151404},
             {position: -0.0002489970092301233},
             {position: -0.0006123348856552688},
             {position: 0.0},
             {position: 0.0002454776121572339},
             {position: -0.0006125097631605818},
             {position: 0.0},
             {position: -6.011625649360198e-05},
             {position: -7.525237853201749e-05},
             {position: 0.0004589365487581964},
             {position: -2.5768562279686937e-08},
             {position: 3.6952027864711024e-09},
             {position: -1.215439818640452e-07},
             {position: -0.00018685885013609092},
             {position: -0.00012379794843505},
             {position: 0.00018816299418880392},
             {position: 0.0},
             {position: 0.00012545830723318857},
             {position: 0.00018820182461462082},
             {position: 0.0},
             {position: -0.0002965242284351066},
             {position: -7.421490458325088e-05},
             {position: 0.00029780157113321477},
             {position: 0.0},
             {position: 7.519586381252998e-05},
             {position: 0.0002978155233687365},
             {position: 0.0},
             {position: -0.00031162847030187843},
             {position: -0.00011780201697139905},
             {position: 0.0003132331027418782},
             {position: 0.0},
             {position: 0.00011936898553119823},
             {position: 0.0003132682590434419},
             {position: 0.0},
             {position: -0.0005479879590994546},
             {position: 0.00226420636694613},
             {position: -0.004706398251618201},
             {position: 0.00244219188467207},
             {position: -0.0012481383713250913},
             {position: 0.0044718407286648085},
             {position: -0.003223702357339719},
             {position: 0.00022766131810515727},
             {position: -0.00016076978298016086},
             {position: 0.0007290998083599438},
             {position: 6.675500702892921e-09},
             {position: 6.560088130007745e-08},
             {position: 1.8800851704767728e-07},
             {position: -0.00028937970244910364},
             {position: -0.00022800955619899245},
             {position: 0.0002868885857552392},
             {position: 0.0},
             {position: 0.0002247193974805696},
             {position: 0.0002870352101013449},
             {position: 0.0},
             {position: -0.0003257605562552845},
             {position: -0.00010204084091388642},
             {position: 0.00032413179977860686},
             {position: 0.0},
             {position: 0.00010060572508045822},
             {position: 0.0003241611323853675},
             {position: 0.0},
             {position: -0.0006475937548724729},
             {position: -0.00011948736852586772},
             {position: 0.0006450965402925642},
             {position: 0.0},
             {position: 0.00011775542527489722},
             {position: 0.0006451367965972861},
             {position: 0.0}]
# no documentation available for this property
noise_std_dev: 0
