--- name:kuka_iiwa_jnt_pos_ctrl
# Minimum control error (dead zone). If one control error value falls below this minimum, it will be set to zero.
dead_zone:
  data: [0]
# Feed Forward gain. Size has to be the same as size of field_names.
d_gain:
  data: [1.0]
# Unique name for each variable, e.g. joint names in case of a joint space controller.
field_names: ["kuka_lbr_l_joint_5"]
# Maximum control output (saturation). If one output value exceeds maximum, all
# other values will be scaled accordingly. Size has to be the same as size of field_names.
max_control_output:
  data: [100.0]
# Proportional gain. Size has to be the same as size of field_names.
p_gain:
  data: [1.0]
# Feed forward gain. Size has to be the same as size of field_names.
ff_gain:
  data: [0.0]
