--- name:default
# Type of activation function used. See ctrl_lib/ActivationFunction.hpp for details.
activation_function:
  threshold: 0
  type: :NO_ACTIVATION

# Minimum control error (dead zone). If one control error value falls below this minimum, it will be set to zero.
dead_zone:
  data: [0,0,0,0,0,0]
# Feed Forward gain. Size has to be the same as size of field_names.
d_gain:
  data: [0,0,0,0,0,0]
ff_gain:
  data: [0,0,0,0,0,0]
# Unique name for each variable, e.g. joint names in case of a joint space controller.
field_names: ["X", "Y", "Z", "rotZ", "rotY", "rotX"]
# Maximum control output (saturation). If one output value exceeds maximum, all
# other values will be scaled accordingly. Size has to be the same as size of field_names.
max_control_output:
  data: [0.5, 0.5, 0.5, 0.707, 0.707, 0.707]
# Proportional gain. Size has to be the same as size of field_names.
p_gain:
  data: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
